Revert "Updated to ognl-3.4.1"
This reverts commit b2125b8d5f38037ecfdc863fdfca7693cad89e97.

java.lang.NoSuchMethodError: 'java.util.Map ognl.Ognl.createDefaultContext(java.lang.Object, ognl.MemberAccess, ognl.ClassRes
olver, ognl.TypeConverter)'